import Head from "next/head";
import Image from "next/image";
import Link from "next/Link";
import { useEffect, useState } from "react";
import { GetTodoController } from "../../../api/gettodo";
import { TodoController } from "../../../api/controltodo";
import { useRouter } from "next/router";

export default function CRUDEdit() {
  const router = useRouter();
  const [data, setData] = useState([]);
  const [tid, settid] = useState();
  const [note, setnote] = useState("");

  const todolist = async (tid) => {


    const data = await GetTodoController()
      .GetDataTodobyID({ tid })
      .then((response) => {
        setnote(response.data.data[0].note);
        settid(response.data.data[0].tid);
        console.log("data TODO List", response);
      });

    setData(data);
  };

  //อัปเดตข้อมูล
  async function EditItem(e) {
    e.preventDefault();

    try {
      await TodoController().Updatetodo({
        tid,
        note,
      });
      console.log("Item Edit successfully");
      alert("Item Edit successfully");
      window.location.replace("/crud");
    } catch (error) {
      console.error("Error Edit item:", error.message);
    }
  }

  useEffect(() => {
    
    if(router.query?.tid){
      todolist(router.query?.tid);
    }
    
    console.log(Number(router.query?.tid));
  }, [router]);

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col  bg-gradient-to-r from-purple-300 to-pink-300">
        {/* start : navbar */}
        <div className="navbar bg-base-100 ">
          <div className="flex-1">
            <a className="btn btn-ghost normal-case text-xl">CRUDNext</a>
          </div>
          <div className="flex-none">
            <div className="mr-5">
              <Link href="/crud">CRUD</Link>
            </div>
            <div className="dropdown dropdown-end">
              <label tabIndex={0} className="btn btn-ghost btn-circle">
                <div className="indicator">
                  <span className="badge badge-sm indicator-item">8</span>
                </div>
              </label>
              <div
                tabIndex={0}
                className="mt-3 card card-compact dropdown-content w-52 bg-base-100 shadow"
              >
                <div className="card-body">
                  <span className="font-bold text-lg">8 Items</span>
                  <span className="text-info">Subtotal: $999</span>
                  <div className="card-actions">
                    <button className="btn btn-primary btn-block">
                      View cart
                    </button>
                  </div>
                </div>
              </div>
            </div>
            <div className="dropdown dropdown-end">
              <label tabIndex={0} className="btn btn-ghost btn-circle avatar">
                <div className="w-10 rounded-full">
                  <Image
                    src="/user.jpg"
                    alt="Vercel Logo"
                    className="dark:invert"
                    width={100}
                    height={24}
                    priority
                  />
                </div>
              </label>
              <ul
                tabIndex={0}
                className="menu menu-sm dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52"
              >
                <li>
                  <Link href="/profile" className="justify-between">
                    Profile
                    <span className="badge">New</span>
                  </Link>
                </li>
                <li>
                  <a>Settings</a>
                </li>
                <li>
                  <Link href="/">Logout</Link>
                </li>
              </ul>
            </div>
          </div>
        </div>
        {/* end : navbar */}
        {/* start : content */}

        <div className="rounded-[10px] bg-white shadow-md lg:ml-16 lg:mr-16 lg:mb-5 lg:mt-16 mt-5 mr-5 ml-5 mb-5 px-[25px] py-[40px] ">
          <div className="grid grid-cols-12 gap-0 mt-5 intro-y">
            <div className="col-span-12 intro-y lg:col-span-6 rounded-md -mt-4">
              <Image
                src="/pics.jpg"
                alt="Vercel Logo"
                className="dark:invert"
                width={900}
                height={900}
                priority
              />
            </div>

            <div className="col-span-12 lg:col-span-6">
              <div className="text-2xl font-bold text-center">Edit Item</div>

              <div className="p-3 w-full">
                <div className="rounded-md shadow-md">
                  <form onSubmit={EditItem}>
                    <div className="form-control w-full p-3">
                      <label className="label">
                        <span className="label-text">tid</span>
                      </label>
                      <input
                        type="text"
                        placeholder="Type here"
                        className="input input-bordered w-full bg-white"
                        value={tid}
                        onChange={(e) => settid(e.target.value)}
                      />
                    </div>
                    <div className="form-control w-full p-3">
                      <label className="label">
                        <span className="label-text">note</span>
                      </label>
                      <input
                        type="text"
                        placeholder="Type here"
                        className="input input-bordered w-full bg-white"
                        value={note}
                        onChange={(e) => setnote(e.target.value)}
                      />
                    </div>

                    <div className="p-3">
                      <button
                        type="submit"
                        className="btn w-full bg-gradient-to-r from-purple-500 to-pink-500 text-white mt-12"
                      >
                        Edit Item
                      </button>
                    </div>
                    <div className="p-3">
                      <Link href="/crud">
                        <button
                          type="submit"
                          className="btn w-full bg-gradient-to-r from-gray-500 to-gray-100 text-white mt-12"
                        >
                          Cancel
                        </button>
                      </Link>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* end : content */}

        <div className="btm-nav lg:hidden">
          <button>
            <span className="btm-nav-label">Home</span>
          </button>
          <button className="active">
            <span className="btm-nav-label">Warnings</span>
          </button>
          <button>
            <span className="btm-nav-label">logout</span>
          </button>
        </div>
      </main>
    </div>
  );
}
