//profile
import Head from "next/head";
import Image from "next/image";
import Link from "next/Link";
import '../styles/globals.css'
import { useEffect, useState } from "react";
import { GetuserController } from "../../api/getdata";
import { CreateController } from "../../api/controluser";

export default function Profile() {
  const [data, setData] = useState([]);
  const [_id, setButtonValue] = useState(0);

  const [countuser, setcountuser] = useState([]);
  const [list, setlist] = useState([]);

  const userlist = async () => {
    const data = await GetuserController()
      .GetDataUser()
      .then((response) => {
        setlist(response.data.data);
        setcountuser(response.data.data.length);
        console.log("data TODO List", response);
      });

    setData(data);
  };

  //ลบข้อมูล
  async function deleteItem(e) {
    console.log(e.target.value);

    try {
      await CreateController().DeleteUser({ _id: e.target.value });
      console.log("Item deleted successfully");
      alert("Item deleted successfully");
      window.location.reload();
    } catch (error) {
      // Handle error
      console.error("Error deleting item:", error.message);
    }
  }
  //ส่งข้อมูลไปหน้าแก้ไข
  async function EditItem(e) {
    setButtonValue(e.target.value);
    window.location.replace(`/profileuser/` + e.target.value);
  }

  useEffect(() => {
    userlist();
  }, []);

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col  bg-gradient-to-r from-purple-300 to-pink-300">
        {/* start : navbar */}
        <div className="navbar bg-base-100 ">
          <div className="flex-1">
            <a className="btn btn-ghost normal-case text-xl">CRUDNext</a>
          </div>
          <div className="flex-none">
            <div className="mr-5">
              <Link href="/crud">CRUD</Link>
            </div>
            <div className="dropdown dropdown-end">
              <label tabIndex={0} className="btn btn-ghost btn-circle">
                <div className="indicator">
                  <span className="badge badge-sm indicator-item">8</span>
                </div>
              </label>
              <div
                tabIndex={0}
                className="mt-3 card card-compact dropdown-content w-52 bg-base-100 shadow"
              >
                <div className="card-body">
                  <span className="font-bold text-lg">8 Items</span>
                  <span className="text-info">Subtotal: $999</span>
                  <div className="card-actions">
                    <button className="btn btn-primary btn-block">
                      View cart
                    </button>
                  </div>
                </div>
              </div>
            </div>
            <div className="dropdown dropdown-end">
              <label tabIndex={0} className="btn btn-ghost btn-circle avatar">
                <div className="w-10 rounded-full">
                  <Image
                    src="/user.jpg"
                    alt="Vercel Logo"
                    className="dark:invert"
                    width={100}
                    height={24}
                    priority
                  />
                </div>
              </label>
              <ul
                tabIndex={0}
                className="menu menu-sm dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52"
              >
                <li>
                  <Link href="/profileuser" className="justify-between">
                    Profile
                    <span className="badge">New</span>
                  </Link>
                </li>
                <li>
                  <a>Settings</a>
                </li>
                <li>
                  <Link href="/">Logout</Link>
                </li>
              </ul>
            </div>
          </div>
        </div>
        {/* end : navbar */}
        {/* start : list */}
        <div className="rounded-[10px] bg-white shadow-md lg:ml-16 lg:mr-16 lg:mb-16 lg:mt-5  mr-5 ml-5 mb-24 px-[25px] py-[40px] ">
          <div></div>
          <div className="">
            <div className="font-bold"> List User = {countuser}</div>
            <div className="overflow-x-auto">
              <table className="table table-zebra">
                {/* head */}
                <thead>
                  <tr>
                    <th className="w-[200px]">imgprofile</th>
                    <th className="w-[200px]">username</th>
                    <th className="w-[200px]">name</th>
                    <th className="w-[200px]">email</th>
                    <th className="w-[200px]">phone_number</th>
                    <th className="w-[200px]">age</th>
                    <th className="w-[200px]">date_of_birth</th>
                  </tr>
                </thead>
                <tbody>
                  {list.map((item, index) => (
                    <tr key={index}>
                      <td>
                        <img src={item.image_profile} />
                      </td>
                      <td>{item.username}</td>
                      <td>
                        {item.name.first} {item.name.last}
                      </td>
                      <td>{item.email}</td>

                      <td>{item.phone_number}</td>
                      <td>{item.age}</td>
                      <td>{item.date_of_birth}</td>
                      <td>
                        <div className="">
                          <button
                            className="bg-red-500 text-white rounded-md px-2 py-1 mr-2"
                            value={item._id}
                            onClick={deleteItem}
                          >
                            ลบ
                          </button>

                          <button
                            className="bg-yellow-400 text-white rounded-md px-2 py-1"
                            value={item._id}
                            onClick={EditItem}
                          >
                            แก้ไข
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
        {/* end : list */}

        <div className="btm-nav lg:hidden">
          <button>
            <span className="btm-nav-label">Home</span>
          </button>
          <button className="active">
            <span className="btm-nav-label">Warnings</span>
          </button>
          <button>
            <span className="btm-nav-label">logout</span>
          </button>
        </div>
      </main>
    </div>
  );
}
